### ISSUE TITLE
Finesse UI

### ISSUE THREAD

**Issue by rachelsoae** [EverUse/EverUse-FE#49]
Products component:
- [x] height of section
- [x] text decoration
- [x] product titles - add a space between 2-word titles (use helper function?)

General
- [x] background color on product detail page
- [x] fonts - use Open Sans, different font weights for headers vs body text
- [x] create a mixin for consistent button styling
- [x] box border mixin

**Comment by rachelsoae** [comment]
Product Detail page:

- [ ] set default selection to "one size" if that is the only size option
- [ ] set default quantity to 1

**Comment by alivaditis** [comment]
Product detail page
- [ ] automatically selected size if it is only onesize

**Comment by rachelsoae** [comment]
- [ ] footer background color

**Comment by rachelsoae** [comment]
Shopping Bag:

- [ ] box shadow

**Comment by rachelsoae** [comment]
FIX BUG:

- [ ] ensure all font variables have been replaced

**Comment by JamieCaudill** [comment]
In the latest Navbar PR I changed the footer background color and got rid of the text decoration on the products cards.

**Comment by JamieCaudill** [comment]
Just added Taranveer's camelToPascalCase function to the Products page, so the titles look good now. Will push with next PR

**Comment by rachelsoae** [comment]
- [ ] Nav fonts
